# Generated by Django 6.1 on 2026-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('important', 'Important'), ('maintenance', 'Maintenance')], default='info', max_length=32),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('user', 'user'), ('post', 'post'), ('chat', 'chat')], max_length=10),
        ),
    ]
