# Generated by Django 6.1.1 on 2026-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_add_status_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'Moderatsiya kutilmoqda'), ('approved', 'Tasdiqlangan'), ('sold', 'Sotilgan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20),
        ),
    ]
