# Generated by Django 5.2.9 on 2026-08-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='telegram_gateway_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='telegram_gateway_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
