# Generated by Django 6.1 on 2026-08-13 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pendingregistration_phone_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOutMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('message_id', models.IntegerField()),
                ('pending_token', models.UUIDField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('temporary', 'Temporary'), ('verification_code', 'Verification Code')], default='temporary', max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_out_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['chat_id', 'message_type'], name='accounts_te_chat_id_56dbe3_idx')],
            },
        ),
    ]
