# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_pendingregistration_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pendingregistration",
            name="email_sent_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
