# Generated by Django 6.1 on 2026-08-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('telegram_linked', 'Telegram linked'), ('verified', 'Verified'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
    ]
