# Generated by Django 6.1.1 on 2026-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_pendingregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='market_email_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='market_phone_visible',
            field=models.BooleanField(default=False),
        ),
    ]
